version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.146
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  app-kafka-produser:
    build:
      dockerfile: ./docker/kafka/Dockerfile
      context: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

# docker-compose up -d
# docker-compose run --rm app-kafka-produser composer install
################################################################
# run_producer
# docker-compose run --rm --entrypoint php app-kafka-produser run_producer.php
# Log
# tail data/logs/*.log