version: '3.4'

services:

  app-kafka-consummer:
    build:
      dockerfile: ./docker/kafka/Dockerfile
      context: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

# docker-compose up -d
# docker-compose run --rm app-kafka-consummer composer install
################################################################
# run_consumer
# docker-compose run --rm --entrypoint php app-kafka-consummer run_consumer_low_level.php
# docker-compose run --rm --entrypoint php app-kafka-consummer run_consumer_high_level.php
# Log
# tail data/logs/*.log